EmployeeManagementSystem/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace EmployeeManagementSystem.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

EmployeeManagementSystem/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Employee.Models;
using Employee.Services;
using EmployeeManagementSystem.Enums;
using EmployeeManagementSystem.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace EmployeeManagementSystem.Pages
{
    [Authorize]
    [ValidateAntiForgeryToken]
    public class IndexModel : PageModel
    {
        private readonly EmployeeService _employeeService;
        public readonly DataProtectionHelper _protectionHelper;
        private readonly ExcelService _excelService;

        public IndexModel(
            EmployeeService employeeService,
            DataProtectionHelper protectionHelper,
            ExcelService excelService)
        {
            _employeeService = employeeService;
            _protectionHelper = protectionHelper;
            _excelService = excelService;
        }

        public string CurrentFilter { get; set; }
        public PaginatedList<EmployeeViewModel> ActiveEmployees;

        public async Task<IActionResult> OnGetAsync(string currentFilter, int? pageIndex)
        {
            if (User.IsInRole(UserRole.Admin))
            {
                return RedirectToPage("/Admin/Index");
            }
            ActiveEmployees = await _employeeService.GetActiveEmployeeAsync(currentFilter, pageIndex);
            return Page();
        }

        public async Task<IActionResult> OnGetDeleteAsync(string ID)
        {
            ID = _protectionHelper.Decrypt(ID);
            await _employeeService.DeleteEmployeeAsync(int.Parse(ID));

            return RedirectToPage();
        }

        public async Task<IActionResult> OnGetExcelAsync()
        {
            var dataEmployee = await _employeeService.GetEmployeeExcelAsync();

            var excel = _excelService.DownloadExcelDocument(dataEmployee);

            return File(excel.Content, excel.ContentType, excel.FileName);
        }
    }
}

EmployeeManagementSystem/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace EmployeeManagementSystem.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

EmployeeManagementSystem/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";

    var prevDisabled = !Model.ActiveEmployees.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.ActiveEmployees.HasNextPage ? "disabled" : "";

}
<div class="flex-column">
    <form asp-page="./Index" method="get" class="d-md-flex">
        <input type="text" class="form-control  col-md-4 mt-1 mb-1 mr-2" asp-for="@Model.CurrentFilter" placeholder="Find By Name" />
        <input type="submit" value="Search" class="btn btn-outline-secondary  col-md-2 mt-1 mb-1  mr-2" />

        <a asp-page="./Index" class="btn btn-outline-warning  col-md-2 mt-1 mb-1  mr-2"
           data-toggle="tooltip" data-placement="bottom" title="Reset the filter and show all employee data.">Back to full List</a>
    </form>
</div>

<hr />
<div class="flex-column">
    <div class="d-md-flex">
        <a class="btn btn-outline-primary col-md-2 mt-1 mb-1 mr-2" asp-page="/EmployeeMS/NewEmployee"
           data-toggle="tooltip" data-placement="bottom" title="Insert new employee data.">New Employee</a>
        <a class="btn btn-outline-success col-md-2 mt-1 mb-1  mr-2" asp-page-handler="Excel" 
           data-toggle="tooltip" data-placement="bottom" title="Export all employee data into xlsx file.">Export To Excel</a>
    </div>

</div>

<div class="table-responsive">

    <table class="table table-bordered table-hover table-striped">
        <thead class="thead-dark text-center">
            <tr>
                <th>@Html.DisplayNameFor(model => model.ActiveEmployees[0].EmployeeID)</th>
                <th>@Html.DisplayNameFor(model => model.ActiveEmployees[0].Name)</th>
                <th>@Html.DisplayNameFor(model => model.ActiveEmployees[0].NIK)</th>
                <th>@Html.DisplayNameFor(model => model.ActiveEmployees[0].Email)</th>
                <th>@Html.DisplayNameFor(model => model.ActiveEmployees[0].PhoneNumber)</th>
                <th>@Html.DisplayNameFor(model => model.ActiveEmployees[0].Position)</th>
                <th>@Html.DisplayNameFor(model => model.ActiveEmployees[0].Religion)</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.ActiveEmployees.Count == 0)
            {
                <tr>
                    <td class="text-center" colspan="8">No Employee Data.</td>
                </tr>
            }
            else
            {
                @foreach (var item in Model.ActiveEmployees)
                {
                    <tr onclick="location.href = '@(Url.Page("EmployeeMS/EditEmployee", new { ID = item.ID}))'"
                        data-toggle="tooltip" data-placement="top" title="Click on the row to view detail or edit employee.">
                        <td>@Model._protectionHelper.Decrypt(item.EmployeeID)</td>
                        <td>@item.Name</td>
                        <td>@item.NIK</td>
                        <td>@item.Email</td>
                        <td>@item.PhoneNumber</td>
                        <td>@item.Position</td>
                        <td>@item.Religion</td>
                        <td class="text-center">
                            <a class="btn btn-danger"
                               data-toggle="tooltip" data-placement="bottom" title="Delete this employee data permanently."
                               onclick="return confirm('Are you sure you want to delete this data?');"
                               asp-page-handler="delete" asp-route-ID="@item.ID">
                                Delete
                            </a>
                        </td>
                    </tr>

                }
            }
        </tbody>
    </table>
</div>
<div class="text-center">
    <ul class="pagination justify-content-center">
        <li>
            <a asp-page="./Index"
               asp-route-pageIndex="@(Model.ActiveEmployees.PageIndex - 1)"
               asp-route-currentFilter="@Model.CurrentFilter"
               class="btn btn-outline-primary mr-2 @prevDisabled">
                Prev
            </a>
        </li>
        @for (var i = 1; i <= Model.ActiveEmployees.TotalPages; i++)
        {
            var activeTransPage = Model.ActiveEmployees.PageIndex == i ? "active" : "";
            <li class="page-item mr-1 @activeTransPage"><a asp-page="./Index" asp-route-pageIndex="@i" class="page-link">@i</a></li>
        }

        <li>

            <a asp-page="./Index"
               asp-route-pageIndex="@(Model.ActiveEmployees.PageIndex + 1)"
               asp-route-currentFilter="@Model.CurrentFilter"
               class="btn btn-outline-primary mr-2 @nextDisabled">
                Next
            </a>
        </li>
    </ul>
</div>