EmployeeManagementSystem/Pages/Admin/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Employee.Models;
using Employee.Services;
using EmployeeManagementSystem.Enums;
using EmployeeManagementSystem.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EmployeeManagementSystem.Pages.Admin
{
    [Authorize(Roles = UserRole.Admin)]
    public class IndexModel : PageModel
    {
        private readonly UserAccessService _userAccessService;
        private readonly EmailService _emailService;

        public IndexModel(
            UserAccessService userAccessService,
            EmailService emailService)
        {
            _userAccessService = userAccessService;
            _emailService = emailService;
        }
        public string CurrentFilter { get; set; }
        public PaginatedList<UserAccessViewModel> Users;

        public async Task OnGetAsync(string currentFilter, int? pageIndex)
        {
            Users = await _userAccessService.GetUsersAsync(currentFilter, pageIndex);
        }

        public async Task<IActionResult> OnGetGiveAccessAsync(string email)
        {
            var accessKey = await _userAccessService.GiveUserAccessKeyAsync(email);
            
            //send email
            //var status = await _emailService.SendEmailAsync(email, accessKey, accessKey);
            //set session
            
            return RedirectToPage();
        }

        public async Task<IActionResult> OnGetDeleteAsync(string email)
        {
            await _userAccessService.DeleteUserAccessAsync(email);
            return RedirectToPage();
        }
    }
}

EmployeeManagementSystem/Pages/Admin/Index.cshtml
@page
@model EmployeeManagementSystem.Pages.Admin.IndexModel
@{
}
@{
    ViewData["Title"] = "Admin Portal";

    var prevDisabled = !Model.Users.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.Users.HasNextPage ? "disabled" : "";

}
<div class="flex-column">
    <form asp-page="./Index" method="get" class="d-md-flex">
        <input type="text" class="form-control  col-md-4 mt-1 mb-1 mr-2" asp-for="@Model.CurrentFilter" placeholder="Find By Email" />
        <input type="submit" value="Search" class="btn btn-outline-secondary  col-md-2 mt-1 mb-1  mr-2" />

        <a asp-page="./Index" class="btn btn-outline-warning  col-md-2 mt-1 mb-1  mr-2"
           data-toggle="tooltip" data-placement="bottom" title="Reset the filter and show all user data.">Back to full List</a>
    </form>
</div>

<div class="table-responsive">

    <table class="table table-bordered table-hover table-striped">
        <thead class="thead-dark text-center">
            <tr>
                <th>@Html.DisplayNameFor(model => model.Users[0].UserEmail)</th>
                <th>@Html.DisplayNameFor(model => model.Users[0].Username)</th>
                <th>@Html.DisplayNameFor(model => model.Users[0].Password)</th>
                <th>@Html.DisplayNameFor(model => model.Users[0].AccessGivenOn)</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Users.Count == 0)
            {
                <tr>
                    <td class="text-center" colspan="8">No User Data.</td>
                </tr>
            }
            else
            {
                @foreach (var item in Model.Users)
                {
                    <tr>
                        <td>@item.UserEmail</td>
                        <td>@item.Username</td>
                        <td>@item.Password</td>
                        <td>@item.AccessGivenOn</td>
                        <td class="text-center">
                            @if (!item.HasAccess)
                            {
                                <a class="btn btn-outline-success"
                                   data-toggle="tooltip" data-placement="bottom" title="Generate access key."
                                   onclick="return confirm('Are you sure you want to give access to @item.UserEmail?');"
                                   asp-page-handler="GiveAccess" asp-route-email="@item.UserEmail">
                                    Give Access
                                </a>
                            }
                            @*else
                            {
                                <a class="btn btn-outline-success"
                                   data-toggle="tooltip" data-placement="bottom" title="Update access key."
                                   onclick="return confirm('Are you sure you want to update access key of @item.UserEmail?');"
                                   asp-page-handler="GiveAccess" asp-route-email="@item.UserEmail">
                                    Update Access Key
                                </a>
                            }*@

                            <a class="btn btn-outline-danger"
                               data-toggle="tooltip" data-placement="bottom" title="Delete this user data permanently."
                               onclick="return confirm('Are you sure you want to delete this data?');"
                               asp-page-handler="delete" asp-route-email="@item.UserEmail">
                                Delete
                            </a>
                        </td>
                    </tr>

                }
            }
        </tbody>
    </table>
</div>
<div class="text-center">
    <ul class="pagination justify-content-center">
        <li>
            <a asp-page="./Index"
               asp-route-pageIndex="@(Model.Users.PageIndex - 1)"
               asp-route-currentFilter="@Model.CurrentFilter"
               class="btn btn-outline-primary mr-2 @prevDisabled">
                Prev
            </a>
        </li>
        @for (var i = 1; i <= Model.Users.TotalPages; i++)
        {
            var activeTransPage = Model.Users.PageIndex == i ? "active" : "";
            <li class="page-item mr-1 @activeTransPage"><a asp-page="./Index" asp-route-pageIndex="@i" class="page-link">@i</a></li>
        }

        <li>

            <a asp-page="./Index"
               asp-route-pageIndex="@(Model.Users.PageIndex + 1)"
               asp-route-currentFilter="@Model.CurrentFilter"
               class="btn btn-outline-primary mr-2 @nextDisabled">
                Next
            </a>
        </li>
    </ul>
</div>